spring.application.name=airline-api

spring.datasource.url=jdbc:postgresql://pg-2669cbd8-stu-a8eb.i.aivencloud.com:11292/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect